name = "standalone-comments-server"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "comments-db"
database_id = "11111111-1111-1111-1111-111111111111"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
ALLOWED_ORIGINS = "*"
APP_URL = "https://standalone-comments-server.nova-3bc190.workers.dev"
